export const categoryImages = {
    'school-holidays': 5,
    'public-holidays': 5,
    'observances': 1,
    'politics': 1,
    'conferences': 1,
    'expos': 1,
    'concerts': 1,
    'festivals': 6,
    'performing-arts': 1,
    'sports': 1,
    'community': 1,
    'daylight-savings': 1,
    'airport-delays': 3,
    'severe-weather': 1,
    'disasters': 1,
    'terror': 1,
    'health-warnings': 1,
    'academic': 5
};
